#include "location_text.h"
#include "map_editor.h"
#include "sign_borders.h"
#include "text_preview.h"
#include <QtWidgets>
#include <memory>
using U5::require;
namespace Workshop {
static int word(const QByteArray &b, int at) {
    require(at >= 0 && at + 1 < b.size(), "Truncated text pointer table");
    return uchar(b[at]) | (uchar(b[at + 1]) << 8);
}
static void put(QByteArray &b, int at, int v) {
    require(v <= 32767, "Signs exceed the engine's signed offset limit");
    b[at] = char(v);
    b[at + 1] = char(v >> 8);
}
QVector<SignRecord> readSigns(const QByteArray &b) {
    require(b.size() >= 66, "Signs header is truncated");
    QVector<SignRecord> out;
    QMap<int, int> starts;
    int pos = 66;
    QMap<int, int> mapBytes;
    int previousMap = -1;
    while (pos < b.size() && uchar(b[pos]) != 255) {
        bool padding = true;
        for (int i = pos; i < b.size(); i++)
            if (b[i] != 0) {
                padding = false;
                break;
            }
        if (padding)
            break;
        require(pos + 4 < b.size(), "Truncated sign record");
        int end = b.indexOf('\0', pos + 4);
        require(end >= 0, "Sign text has no terminator");
        SignRecord r{uchar(b[pos]), qint8(b[pos + 1]), uchar(b[pos + 2]), uchar(b[pos + 3]),
                     b.mid(pos + 4, end - pos - 4)};
        require(r.map <= 32 && (r.map == 0 || (r.x < 32 && r.y < 32)), "Invalid sign location");
        require(r.floor >= -1 && r.floor <= 3, "Invalid sign floor");
        require(r.map >= previousMap, "Sign records must be grouped in location order");
        previousMap = r.map;
        mapBytes[r.map] += end - pos + 1;
        require(mapBytes[r.map] < 3000, "Location signs exceed the engine read buffer");
        if (!starts.contains(r.map))
            starts[r.map] = pos;
        out.append(r);
        pos = end + 1;
    }
    bool padding = pos < b.size();
    for (int i = pos; i < b.size(); i++)
        if (b[i] != 0) {
            padding = false;
            break;
        }
    require(pos < b.size() && (uchar(b[pos]) == 255 || padding), "Signs list has no terminator");
    for (int m = 0; m < 33; m++) {
        int offset = word(b, m * 2);
        require(offset == 0 || (starts.contains(m) && starts[m] == offset),
                "Sign header points outside its map's records");
    }
    return out;
}
QByteArray writeSigns(const QByteArray &original, const QVector<SignRecord> &records) {
    const auto before = readSigns(original);
    if (before == records)
        return original;
    for (const auto &r : records) {
        require(r.map >= 0 && r.map <= 32 && r.floor >= -1 && r.floor <= 3,
                "Invalid sign location or floor");
        int side = r.map == 0 ? 256 : 32;
        require(r.x >= 0 && r.x < side && r.y >= 0 && r.y < side,
                "Sign coordinates extend beyond the location map");
    }
    QByteArray out(66, 0);
    QSet<int> seen;
    // Keep record order within each location; the first header byte is the map ID.
    for (int m = 0; m < 33; m++)
        for (const auto &r : records)
            if (r.map == m) {
                require(r.text.indexOf('\0') < 0, "Sign text cannot contain NUL");
                require(!(m == 4 && r.floor == 0 && r.x == 17 && r.y == 21) || before.contains(r),
                        "Yew's wanted poster is generated by the engine");
                if (!seen.contains(m)) {
                    put(out, m * 2, out.size());
                    seen.insert(m);
                }
                out.append(char(m));
                out.append(char(r.floor));
                out.append(char(r.x));
                out.append(char(r.y));
                out.append(r.text);
                out.append('\0');
            }
    for (int m = 0; m < 33; m++)
        if (seen.contains(m)) {
            int size = 0;
            for (const auto &r : records)
                if (r.map == m)
                    size += 5 + r.text.size();
            require(size < 3000, "A location’s signs exceed the engine’s 3000-byte read buffer");
        }
    int tail = 66;
    for (const auto &r : readSigns(original))
        tail += 5 + r.text.size();
    if (uchar(original[tail]) != 255)
        out += char(255);
    out += original.mid(tail);
    require(out.size() <= 32767, "Signs exceed the engine's signed offset limit");
    readSigns(out);
    return out;
}
QString signSource(const QByteArray &b) {
    QString out;
    bool runic = false;
    for (auto c : b) {
        int v = uchar(c);
        bool rune = v >= 32 && v <= 126 && v != 38 && v != 39 && !(v >= 41 && v <= 49) && v != 91 &&
                    v != 93;
        if (rune && !runic) {
            out += "[runes]";
            runic = true;
        }
        if (!rune && runic) {
            out += "[/runes]";
            runic = false;
        }
        if (rune)
            out += QChar(v);
        else if (v == 0x8a)
            out += '\n';
        else if (v >= 0xa0 && v <= 0xfe && (v & 127) != 91 && (v & 127) != 93)
            out += QChar(v & 127);
        else
            out += QString("[byte:%1]").arg(v, 2, 16, QChar('0'));
    }
    if (runic)
        out += "[/runes]";
    return out;
}
QByteArray encodeSign(const QString &s) {
    QByteArray out;
    bool runic = false;
    for (int i = 0; i < s.size(); i++) {
        if (s.mid(i, 7) == "[runes]") {
            require(!runic, "Nested rune spans are invalid");
            runic = true;
            i += 6;
            continue;
        }
        if (s.mid(i, 8) == "[/runes]") {
            require(runic, "Unexpected rune span ending");
            runic = false;
            i += 7;
            continue;
        }
        if (s.mid(i, 6) == "[byte:") {
            require(i + 8 < s.size() && s[i + 8] == ']', "Use [byte:NN] for preserved glyphs");
            bool ok = false;
            int v = s.mid(i + 6, 2).toInt(&ok, 16);
            require(ok && v > 0 && v <= 255, "Invalid sign glyph");
            out += char(v);
            i += 8;
        } else {
            auto c = s[i].unicode();
            require(c == '\n' || (c >= 32 && c <= 126 && c != 91 && c != 93),
                    "Use ASCII letters and formatting buttons");
            require(!runic || c == '\n' || !(c == 38 || c == 39 || (c >= 41 && c <= 49)),
                    "These rune glyphs are engine border shortcuts; use normal lettering instead");
            out += char(c == '\n' ? 0x8a : c | (runic ? 0 : 128));
        }
    }
    require(!runic, "Close the rune span with [/runes]");
    return out;
}
QByteArray description(const QByteArray &b, int entry) {
    require(entry >= 0 && entry < 512 && b.size() >= 1024, "Invalid description entry");
    int pos = word(b, entry * 2);
    require(pos >= 1024 && pos < b.size(), "Description pointer outside text pool");
    int end = b.indexOf('\0', pos);
    require(end >= pos && end - pos < 128, "Description must end within 128 bytes");
    return b.mid(pos, end - pos);
}
QByteArray changeDescription(const QByteArray &b, int entry, const QString &s, bool linked) {
    QByteArray text;
    for (auto c : s) {
        require(c.unicode() == 10 || (c.unicode() >= 32 && c.unicode() <= 126),
                "Descriptions support ASCII and line breaks");
        text += char(c.unicode());
    }
    require(text.size() < 128, "Description is limited to 127 bytes");
    if (description(b, entry) == text)
        return b;
    QByteArray out = b;
    int old = word(b, entry * 2), offset = out.size();
    require(offset + text.size() + 1 <= 65535, "Description text pool exceeds 16-bit limit");
    out += text;
    out += '\0';
    for (int i = 0; i < 512; i++)
        if (i == entry || (linked && word(b, i * 2) == old)) {
            out[i * 2] = char(offset);
            out[i * 2 + 1] = char(offset >> 8);
        }
    return out;
}
static QImage signPreview(const Project &p, const QByteArray &b) {
    QImage image(128, 1024, QImage::Format_RGB32);
    image.fill(Qt::black);
    QPainter painter(&image);
    int x = 0, y = 0;
    auto draw = [&](int c, bool regular) {
        if (c == 10) {
            x = 0;
            y += 8;
            return;
        }
        if (x >= 128) {
            x = 0;
            y += 8;
        }
        if (y >= 1024)
            return;
        QString font = regular ? "IBM.CH" : "RUNES.CH";
        if (p.resources.contains(font))
            painter.drawImage(x, y,
                              previewText(p.data(font), QString(QChar(c)),
                                          regular ? FontMode::Normal : FontMode::Runic, 8)
                                  .image);
        x += 8;
        if (x >= 128) {
            x = 0;
            y += 8;
        }
    };
    for (auto c : b) {
        int v = uchar(c);
        if (v == 13)
            continue;
        if (v >= 0x29 && v <= 0x31) {
            for (auto ch : QString::fromLatin1(engineSignBorders[v - 0x29]))
                draw(ch.unicode(), false);
        } else
            draw(v == 0x26 || v == 0x27 ? 0x6c : v & 127, v & 128);
    }
    painter.end();
    return image.copy(0, 0, 128, qMin(1024, y + 8));
}
QWidget *locationTextEditor(Project *project, const QString &resource, TextCommit commit,
                            QMap<QString, int> *state, std::function<bool()> *flush) {
    auto root = new QWidget;
    auto layout = new QVBoxLayout(root);
    auto search = new QLineEdit;
    search->setPlaceholderText("Search text or location");
    search->setToolTip("Filter entries by their displayed text or location.");
    layout->addWidget(search);
    auto splitter = new QSplitter;
    splitter->setChildrenCollapsible(false);
    layout->addWidget(splitter, 1);
    auto list = new QListWidget;
    list->setObjectName("locationTextEntries");
    splitter->addWidget(list);
    auto pane = new QWidget;
    auto form = new QVBoxLayout(pane);
    splitter->addWidget(pane);
    splitter->setStretchFactor(1, 2);
    list->setMinimumWidth(180);
    list->setMaximumWidth(420);
    list->setToolTip("Select an entry to inspect its text. Each edit is undoable.");
    auto notice = new QLabel;
    notice->setWordWrap(true);
    form->addWidget(notice);
    auto text = new QPlainTextEdit;
    text->setObjectName("locationTextDraft");
    form->addWidget(text);
    auto preview = new QLabel;
    auto scroll = new QScrollArea;
    scroll->setMaximumHeight(180);
    scroll->setWidget(preview);
    form->addWidget(scroll);
    auto apply = new QPushButton("Apply text");
    apply->setToolTip("Commit this text as one undoable edit; terrain is never changed.");
    form->addWidget(apply);
    if (flush)
        *flush = [=] {
            if (!text->document()->isModified())
                return true;
            apply->click();
            return !text->document()->isModified();
        };
    auto selectedRow = std::make_shared<int>(-1);
    auto mayDiscard = [=](int row) {
        if (row < 0)
            return false;
        if (text->document()->isModified() &&
            QMessageBox::question(
                root, "Unapplied text",
                "Discard the text changes? Choose No, then Apply text to save them.",
                QMessageBox::Yes | QMessageBox::No, QMessageBox::No) != QMessageBox::Yes) {
            QSignalBlocker block(list);
            list->setCurrentRow(*selectedRow);
            return false;
        }
        *selectedRow = row;
        return true;
    };
    if (resource == "LOOK2.DAT") {
        auto bank = new QComboBox;
        bank->addItems({"Terrain and objects", "Actors"});
        bank->setToolTip("Select which engine description table to edit.");
        layout->insertWidget(0, bank);
        text->setToolTip("Enter up to 127 ASCII characters, including line breaks. The preview "
                         "uses the game’s normal font.");
        auto lineBreak = new QPushButton("Insert line break");
        lineBreak->setToolTip("Begin a new line in the game’s Look text window.");
        form->insertWidget(2, lineBreak);
        QObject::connect(lineBreak, &QPushButton::clicked, root,
                         [=] { text->insertPlainText("\n"); });
        auto linked = new QCheckBox("Change all entries sharing this text");
        linked->setToolTip("Off by default: only the selected entry changes. On: update every "
                           "pointer sharing its text.");
        form->insertWidget(1, linked);
        if (project->resources.contains("TILES.16")) {
            auto tiles = U5::readGraphics("TILES.16", project->data("TILES.16")).images;
            for (int i = 0; i < 512; i++) {
                auto item = new QListWidgetItem(
                    QString("%1 · %2").arg(
                        MapDocument::tileName(i % 256),
                        QString::fromLatin1(description(project->data(resource), i))),
                    list);
                item->setData(Qt::UserRole, i);
                if (i % 256 < tiles.size())
                    item->setIcon(QPixmap::fromImage(tiles[i % 256]));
            }
        }
        auto filter = [=] {
            for (int i = 0; i < list->count(); i++)
                list->item(i)->setHidden(
                    i / 256 != bank->currentIndex() ||
                    !list->item(i)->text().contains(search->text(), Qt::CaseInsensitive));
            if (!list->currentItem() || list->currentItem()->isHidden())
                for (int i = 0; i < list->count(); ++i)
                    if (!list->item(i)->isHidden()) {
                        list->setCurrentRow(i);
                        break;
                    }
        };
        QObject::connect(bank, &QComboBox::currentIndexChanged, root, filter);
        QObject::connect(search, &QLineEdit::textChanged, root, filter);
        QObject::connect(list, &QListWidget::currentRowChanged, root, [=](int row) {
            if (!mayDiscard(row))
                return;
            text->setPlainText(QString::fromLatin1(description(project->data(resource), row)));
            int n = 0;
            for (int i = 0; i < 512; i++)
                if (word(project->data(resource), i * 2) == word(project->data(resource), row * 2))
                    n++;
            notice->setText(QString("Used by Look command for %1. %2 entries share this text. "
                                    "Engine-generated special descriptions override some tiles.")
                                .arg(MapDocument::tileName(row % 256))
                                .arg(n));
        });
        QObject::connect(text, &QPlainTextEdit::textChanged, root, [=] {
            if (project->resources.contains("IBM.CH")) {
                auto result = previewText(project->data("IBM.CH"), text->toPlainText(),
                                          FontMode::Normal, 128);
                preview->setPixmap(
                    QPixmap::fromImage(result.image).scaled(result.image.size() * 2));
                preview->adjustSize();
            }
        });
        QObject::connect(apply, &QPushButton::clicked, root, [=] {
            try {
                int row = list->currentRow();
                if (row < 0)
                    return;
                auto bytes = changeDescription(project->data(resource), row, text->toPlainText(),
                                               linked->isChecked());
                if (commit({{resource, bytes}}, "Edit description")) {
                    text->document()->setModified(false);
                    for (int i = 0; i < 512; i++)
                        list->item(i)->setText(
                            MapDocument::tileName(i % 256) + " · " +
                            QString::fromLatin1(description(project->data(resource), i)));
                }
            } catch (const std::exception &e) {
                QMessageBox::warning(root, "Cannot apply text", e.what());
            }
        });
        list->setCurrentRow(0);
        filter();
    } else {
        auto records = std::make_shared<QVector<SignRecord>>(readSigns(project->data(resource)));
        auto location = new QComboBox;
        location->setToolTip(
            "Select an existing location floor. Only floors present in the map files are offered.");
        layout->insertWidget(0, location);
        struct Page {
            QString resource;
            int index, map, floor;
        };
        auto pages = std::make_shared<QVector<Page>>();
        if (project->resources.contains("BRIT.DAT")) {
            pages->append({"BRIT.DAT", 0, 0, 0});
            location->addItem("Britannia");
        }
        QStringList resources = {"TOWNE.DAT", "DWELLING.DAT", "CASTLE.DAT", "KEEP.DAT"};
        for (int group = 0; group < 4; group++) {
            auto name = resources[group];
            if (!project->resources.contains(name))
                continue;
            auto maps = U5::mapPages(name, project->data(name));
            for (int i = 0; i < maps.size(); i++) {
                auto m = maps[i];
                pages->append({name, i, group * 8 + m.settlement + 1, m.floor});
                location->addItem(m.name);
            }
        }
        auto place = new QComboBox;
        place->setObjectName("signLocation");
        location->setObjectName("signFloor");
        place->setToolTip("Choose the location whose signs and floors to inspect.");
        layout->insertWidget(0, place);
        QSet<int> addedMaps;
        for (int i = 0; i < pages->size(); i++) {
            auto p = pages->at(i);
            if (!addedMaps.contains(p.map)) {
                QString title = location->itemText(i).section(" — ", 0, 0);
                place->addItem(title, p.map);
                addedMaps.insert(p.map);
            }
        }
        int initial = pages->isEmpty() ? -1
                      : state ? qBound(0, state->value("SIGNS.DAT/page"), int(pages->size()) - 1)
                              : 0;
        auto fillFloors = [=](int preferred) {
            QSignalBlocker block(location);
            location->clear();
            for (int i = 0; i < pages->size(); i++) {
                auto p = pages->at(i);
                if (p.map == place->currentData().toInt())
                    location->addItem(p.floor < 0    ? "Basement"
                                      : p.floor == 0 ? "Ground floor"
                                                     : QString("Floor %1").arg(p.floor),
                                      i);
            }
            int row = location->findData(preferred);
            location->setCurrentIndex(row < 0 ? 0 : row);
        };
        if (initial >= 0 && initial < pages->size())
            place->setCurrentIndex(place->findData(pages->at(initial).map));
        fillFloors(initial);
        auto canvas = new MapCanvas;
        canvas->setObjectName("signMap");
        canvas->tool = MapCanvas::InspectNpc;
        canvas->zoom = 1;
        canvas->tiles = U5::readGraphics("TILES.16", project->data("TILES.16")).images;
        auto mapScroll = new QScrollArea;
        mapScroll->setWidget(canvas);
        form->insertWidget(0, mapScroll, 1);
        auto add = new QPushButton("Add sign at selected cell");
        add->setToolTip("Add a text record at the selected map cell without painting terrain. Use "
                        "Look on a sign tile to read it.");
        form->addWidget(add);
        auto controls = new QHBoxLayout;
        auto x = new QSpinBox;
        auto y = new QSpinBox;
        x->setRange(0, 255);
        y->setRange(0, 255);
        x->setToolTip("Sign's east-west coordinate. Changes move the record, not the terrain.");
        y->setToolTip("Sign's north-south coordinate.");
        controls->addWidget(new QLabel("X"));
        controls->addWidget(x);
        controls->addWidget(new QLabel("Y"));
        controls->addWidget(y);
        form->insertLayout(1, controls);
        notice->setText(
            "Plain text uses normal lettering; [runes]…[/runes] selects runic lettering. Preserved "
            "[byte:NN] tokens represent borders or pauses. Maps without a matching record show the "
            "engine's Eight Laws; Yew's wanted poster is generated and cannot be edited here.");
        text->setToolTip("ASCII letters use the normal font; [byte:NN] preserves exact runic or "
                         "decorative glyphs. Newlines use normal-font line breaks.");
        QObject::connect(x, &QSpinBox::valueChanged, root,
                         [=] { text->document()->setModified(true); });
        QObject::connect(y, &QSpinBox::valueChanged, root,
                         [=] { text->document()->setModified(true); });
        auto refresh = [=] {
            QSignalBlocker block(list), bx(x), by(y);
            list->clear();
            canvas->actors.clear();
            int p = location->currentData().isValid() ? location->currentData().toInt() : -1;
            if (p < 0)
                return;
            if (state)
                (*state)["SIGNS.DAT/page"] = p;
            auto page = pages->at(p);
            MapDocument doc(project, page.resource);
            canvas->side = doc.pages[page.index].side;
            canvas->ids = doc.terrain(page.index);
            canvas->original = canvas->ids;
            x->setMaximum(canvas->side - 1);
            y->setMaximum(canvas->side - 1);
            for (int i = 0; i < records->size(); i++) {
                auto r = records->at(i);
                if (r.map != page.map || r.floor != page.floor ||
                    (r.map == 4 && r.floor == 0 && r.x == 17 && r.y == 21))
                    continue;
                auto item = new QListWidgetItem(QString("(%1,%2) %3")
                                                    .arg(r.x)
                                                    .arg(r.y)
                                                    .arg(signSource(r.text).simplified().left(80)),
                                                list);
                item->setData(Qt::UserRole, i);
                item->setToolTip(
                    "Text is read with Look; adding a record does not add a sign tile.\n" +
                    signSource(r.text));
                canvas->actors.append({r.x, r.y, -1, i, "Sign"});
            }
            if (page.map == 4 && page.floor == 0)
                canvas->actors.append({17, 21, -1, -1, "Generated"});
            canvas->resizeMap();
            canvas->update();
        };
        auto previousPage = std::make_shared<int>(initial);
        auto changeFloor = [=] {
            if (text->document()->isModified() &&
                QMessageBox::question(root, "Unapplied sign", "Discard unapplied sign text?",
                                      QMessageBox::Yes | QMessageBox::No,
                                      QMessageBox::No) != QMessageBox::Yes) {
                QSignalBlocker bp(place);
                place->setCurrentIndex(place->findData(pages->at(*previousPage).map));
                fillFloors(*previousPage);
                return;
            }
            text->document()->setModified(false);
            text->clear();
            *selectedRow = -1;
            *previousPage = location->currentData().isValid() ? location->currentData().toInt() : 0;
            refresh();
            if (list->count())
                list->setCurrentRow(0);
        };
        QObject::connect(location, &QComboBox::currentIndexChanged, root, changeFloor);
        QObject::connect(place, &QComboBox::currentIndexChanged, root, [=] {
            fillFloors(-1);
            changeFloor();
        });
        QObject::connect(search, &QLineEdit::textChanged, root, [=] {
            for (int i = 0; i < list->count(); i++)
                list->item(i)->setHidden(
                    !list->item(i)->text().contains(search->text(), Qt::CaseInsensitive));
        });
        QObject::connect(list, &QListWidget::currentRowChanged, root, [=](int row) {
            if (!mayDiscard(row))
                return;
            auto r = records->at(list->item(row)->data(Qt::UserRole).toInt());
            {
                QSignalBlocker bx(x), by(y);
                x->setValue(r.x);
                y->setValue(r.y);
            }
            text->setPlainText(signSource(r.text));
            int tile = uchar(canvas->ids[r.y * canvas->side + r.x]);
            bool readable =
                tile == 0x89 || tile == 0x8a || tile == 0xa0 || tile == 0xa4 || tile == 0xf8;
            notice->setText(
                QString("%1 Plain text is normal lettering; [runes]…[/runes] selects runes. "
                        "Terrain is never painted automatically. The engine generates the Eight "
                        "Laws fallback and Yew’s wanted poster.")
                    .arg(readable ? "Look reads this sign tile."
                                  : "Warning: this tile does not read SIGNS.DAT with Look."));
            canvas->keyboardCell = {r.x, r.y};
            QTimer::singleShot(0, root, [=] {
                mapScroll->ensureVisible((r.x + 0.5) * 16 * canvas->zoom,
                                         (r.y + 0.5) * 16 * canvas->zoom, 30, 30);
            });
            canvas->selectedNpc = list->item(row)->data(Qt::UserRole).toInt();
            canvas->update();
        });
        QObject::connect(text, &QPlainTextEdit::textChanged, root, [=] {
            try {
                auto image = signPreview(*project, encodeSign(text->toPlainText()));
                preview->setPixmap(QPixmap::fromImage(image).scaled(image.size() * 2));
                preview->adjustSize();
            } catch (const std::exception &) {
                preview->setText("Incomplete glyph token; correct it before applying.");
            }
        });
        QObject::connect(apply, &QPushButton::clicked, root, [=] {
            try {
                auto item = list->currentItem();
                if (!item)
                    return;
                auto next = *records;
                auto &r = next[item->data(Qt::UserRole).toInt()];
                r.x = x->value();
                r.y = y->value();
                r.text = encodeSign(text->toPlainText());
                auto bytes = writeSigns(project->data(resource), next);
                if (commit({{resource, bytes}}, "Edit sign")) {
                    text->document()->setModified(false);
                    int row = list->currentRow();
                    *records = next;
                    refresh();
                    if (row >= 0 && row < list->count())
                        list->setCurrentRow(row);
                }
            } catch (const std::exception &e) {
                QMessageBox::warning(root, "Cannot apply sign", e.what());
            }
        });
        QObject::connect(add, &QPushButton::clicked, root, [=] {
            if (text->document()->isModified()) {
                apply->click();
                if (text->document()->isModified())
                    return;
            }
            try {
                int p = location->currentData().isValid() ? location->currentData().toInt() : -1;
                if (p < 0)
                    return;
                auto page = pages->at(p);
                auto cell = canvas->selection.isEmpty() ? canvas->keyboardCell
                                                        : canvas->selection.topLeft();
                auto next = *records;
                for (auto r : next)
                    require(r.map != page.map || r.floor != page.floor || r.x != cell.x() ||
                                r.y != cell.y(),
                            "A sign already exists here");
                next.append({page.map, page.floor, cell.x(), cell.y(), encodeSign("New sign")});
                auto bytes = writeSigns(project->data(resource), next);
                if (commit({{resource, bytes}}, "Add sign")) {
                    *records = next;
                    refresh();
                    list->setCurrentRow(list->count() - 1);
                }
            } catch (const std::exception &e) {
                QMessageBox::warning(root, "Cannot add sign", e.what());
            }
        });
        canvas->chooseNpc = [=](int id) {
            for (int row = 0; row < list->count(); row++)
                if (list->item(row)->data(Qt::UserRole).toInt() == id)
                    list->setCurrentRow(row);
        };
        auto lettering = new QPushButton("Runic lettering");
        lettering->setToolTip("Wrap selected ASCII letters in a runic span. Decorative borders and "
                              "shortcuts remain preserved glyph tokens.");
        form->insertWidget(3, lettering);
        QObject::connect(lettering, &QPushButton::clicked, root, [=] {
            auto cursor = text->textCursor();
            QString selected = cursor.selectedText();
            selected.replace(QChar(0x2029), QChar(10));
            cursor.insertText("[runes]" + selected + "[/runes]");
        });
        auto remove = new QPushButton("Delete sign record");
        remove->setToolTip("Remove only this text record. Terrain is unchanged; Look then uses the "
                           "engine fallback.");
        form->addWidget(remove);
        QObject::connect(remove, &QPushButton::clicked, root, [=] {
            if (text->document()->isModified()) {
                apply->click();
                if (text->document()->isModified())
                    return;
            }
            auto item = list->currentItem();
            if (!item)
                return;
            if (QMessageBox::question(root, "Delete sign",
                                      "Delete this sign record? Terrain will remain unchanged.") !=
                QMessageBox::Yes)
                return;
            try {
                auto next = *records;
                next.removeAt(item->data(Qt::UserRole).toInt());
                auto bytes = writeSigns(project->data(resource), next);
                if (commit({{resource, bytes}}, "Delete sign")) {
                    *records = next;
                    refresh();
                }
            } catch (const std::exception &e) {
                QMessageBox::warning(root, "Cannot delete sign", e.what());
            }
        });
        refresh();
        if (list->count())
            list->setCurrentRow(0);
    }
    return root;
}
} // namespace Workshop
